version: "3.7"

services:
  caddy:
    container_name: humanbios-fb
    image: humanbios-fb
    restart: unless-stopped
    ports:
    - 8443:8443

networks:
  default:
    external:
      name: caddynet
